[[[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\__init__.py","","",null,0],[false,[["Audio",true,2,["Audio",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\audio.py","","",null,0],5]],["ChatCompletion",true,2,["ChatCompletion",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\chat_completion.py","","",null,0],5]],["Completion",true,2,["Completion",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\completion.py","","",null,0],5]],["Customer",true,2,["Customer",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\customer.py","","",null,0],5]],["Edit",true,2,["Edit",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\edit.py","","",null,0],5]],["Deployment",true,2,["Deployment",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\deployment.py","","",null,0],5]],["Embedding",true,2,["Embedding",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\embedding.py","","",null,0],5]],["Engine",true,2,["Engine",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\engine.py","","",null,0],5]],["ErrorObject",true,2,["ErrorObject",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\error_object.py","","",null,0],5]],["File",true,2,["File",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\file.py","","",null,0],5]],["FineTune",true,2,["FineTune",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\fine_tune.py","","",null,0],5]],["Image",true,2,["Image",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\image.py","","",null,0],5]],["Model",true,2,["Model",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\model.py","","",null,0],5]],["Moderation",true,2,["Moderation",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\api_resources\\moderation.py","","",null,0],5]],["APIError",true,2,["APIError",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\error.py","","",null,0],5]],["InvalidRequestError",true,2,["InvalidRequestError",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\error.py","","",null,0],5]],["OpenAIError",true,2,["OpenAIError",[0,"c:\\Users\\Самир\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openai\\error.py","","",null,0],5]],["api_key",true,13,null],["api_key_path",true,13,null],["organization",true,13,null],["api_base",true,13,null],["api_type",true,13,null],["api_version",true,13,null],["verify_ssl_certs",true,13,null],["proxy",true,13,null],["app_info",true,13,null],["enable_telemetry",true,13,null],["ca_bundle_path",true,13,null],["debug",true,13,null],["log",true,13,null],["aiosession",true,13,null],["__all__",true,13,null]]]]]